// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYkfqqxXYV1xHC79Z5x4NWTefbPIgvKfM',
    appId: '1:531463712974:web:86794ee1b969ec0590609f',
    messagingSenderId: '531463712974',
    projectId: 'afghanlance-app',
    authDomain: 'afghanlance-app.firebaseapp.com',
    storageBucket: 'afghanlance-app.firebasestorage.app',
    measurementId: 'G-3E972YGCLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3Q-z9JBiPFNLng4br6iBzBIzF3IlCy0',
    appId: '1:531463712974:android:a641a03fd564299b90609f',
    messagingSenderId: '531463712974',
    projectId: 'afghanlance-app',
    storageBucket: 'afghanlance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgkvCakz0vSAQmbwPtZKrPqbLNNJwkh4',
    appId: '1:531463712974:ios:98227c7b097ac90390609f',
    messagingSenderId: '531463712974',
    projectId: 'afghanlance-app',
    storageBucket: 'afghanlance-app.firebasestorage.app',
    iosClientId: '531463712974-ns92pahact2i4n1vs57njos2s1f2hbi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.afghanlance',
  );
}
