import 'package:afghanlance/welcome_page.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'auth_gate.dart';
import 'firebase_options.dart'; // generated by Firebase CLI

import 'constants.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const AfghanLance());
}

class AfghanLance extends StatefulWidget {
  const AfghanLance({super.key});

  @override
  State<AfghanLance> createState() => _AfghanLanceState();
}

class _AfghanLanceState extends State<AfghanLance> {
  ThemeMode _themeMode = ThemeMode.light;

  void toggleTheme() {
    setState(() {
      _themeMode = _themeMode == ThemeMode.light
          ? ThemeMode.dark
          : ThemeMode.light;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: _themeMode,

      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: kFirstColor,
        primaryColor: kThirdColor,
        colorScheme: const ColorScheme.light(primary: kThirdColor),
      ),

      darkTheme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF121212),
        primaryColor: kThirdColor,
        colorScheme: const ColorScheme.dark(
          primary: kThirdColor,
          surface: Color(0xFF1E1E1E),
        ),
      ),

     home: AuthGate(onToggleTheme: toggleTheme),
      //home: WelcomePageOne(onToggleTheme: toggleTheme),
    );
  }
}
